version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: veipranges
       MYSQL_USER: laravel
       MYSQL_PASSWORD: laravel

   php:
     depends_on:
       - db
     image: php:7.2-apache
     volumes:
       - ./html:/var/www/html
       - ./logs/apache2-access.log:/var/log/apache2/access.log
       - ./logs/apache2-error.log:/var/log/apache2/error.log
     ports:
       - "8081:80"
     restart: always
     #environment:
       #WORDPRESS_DB_HOST: db:3306
       #WORDPRESS_DB_PASSWORD: laravel

   phpmyadmin:
     depends_on:
       - db
     image: phpmyadmin/phpmyadmin:latest
     ports:
       - 9091:80
     restart: always

volumes:
    db_data:
